//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cons.Promerica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formato_Mensaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formato_Mensaje()
        {
            this.Mensaje = new HashSet<Mensaje>();
        }
    
        public int FormatoMensajeId { get; set; }
        public byte IdTipo { get; set; }
        public byte IdTipoInformacion { get; set; }
        public string Nombre { get; set; }
        public string Remitente { get; set; }
        public string Asunto { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        public virtual Tipo_Informacion Tipo_Informacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensaje> Mensaje { get; set; }
    }
}
