//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cons.Promerica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int MensajeId { get; set; }
        public int IdFormatoMensaje { get; set; }
        public int IdProyecto { get; set; }
        public int IdProducto { get; set; }
    
        public virtual Formato_Mensaje Formato_Mensaje { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
